services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    depends_on:
      - php
      - mysql
    container_name: laravel_nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html

  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    container_name: laravel_php
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8.0.27
    platform: linux/amd64
    container_name: laravel_mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: fly_more
      MYSQL_USER: nmk
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root

  composer:
    image: composer:latest
    container_name: laravel_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  artisan:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    container_name: laravel_artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan" ]

  npm:
    image: node:current-alpine
    container_name: laravel_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "npm" ]

  # Queue Worker Service
  laravel-queue-worker:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    container_name: laravel-queue-worker
    tty: true
    environment:
      SERVICE_NAME: laravel-queue-worker
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: php artisan queue:work --queue=rabbitmq --tries=3 --max-time=3600
    restart: always

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: nmk
      RABBITMQ_DEFAULT_PASS: 123456
