name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the docker container
        run: docker compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          while ! docker compose exec -T mysql mysqladmin ping --host=127.0.0.1 --user=root --password=root --silent; do
            sleep 5
          done
          echo "MySQL is ready."

      - name: Install Dependencies
        run: docker compose run --rm composer install --prefer-dist

        # ✅ Run Migrations & Seeders
      - name: Run Migrations
        run: docker compose run --rm artisan migrate --force

        # ✅ Run PHPUnit Tests
      - name: Run Tests
        run: docker compose run --rm artisan test
