name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the docker container
      run: docker compose up -d

    - name: Install Dependencies
      run: docker compose run --rm composer install --prefer-dist

     # ✅ Run Migrations & Seeders
    - name: Run Migrations
      run: docker compose run --rm artisan migrate --force
     
     # ✅ Run PHPUnit Tests
    - name: Run Tests
      run: docker compose run --rm artisan test
